### ISSUE TITLE
数据集质量问题

### ISSUE THREAD

**Issue by hanhanzli** [CURRENTF/HRN#1]
![image](https://github.com/CURRENTF/HRN/assets/85111950/44c9c08f-5cfb-491a-bb7e-cd6a74f7947f)
感觉数据集做得还有很大欠缺，被害人后也跟上了被告人的标签，且事实描述中被告人和参与人没有区分开

**Comment by CURRENTF** [comment]
感谢您指出数据集存在的问题。多犯罪者数据相比于单犯罪者更加复杂，经过匿名化和没有匿名化的数据混杂，在预处理上带来了很多问题。因此极少部分数据可能存在一些问题，我们会在未来的工作里继续优化。此外在我们在论文中的实验设置里已经阐述，我们会将被告的代号作为输入，来预测相关的罪名，法条等。因此这个问题不影响我们论文里的发现和结果。

**Comment by hanhanzli** [comment]
好的 谢谢解答
