### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by winnerLuo** [CURRENTF/HRN#2]
![001](https://github.com/CURRENTF/HRN/assets/70368328/0b5f617f-5ec4-401a-914e-ee974ded4e71)
![002](https://github.com/CURRENTF/HRN/assets/70368328/0756cbc3-e747-4e8c-ad84-3dc153ffa7f6)
以及代码中只有raw_data,没有sub_data文件，希望把完整的项目发送致我的邮箱2963382776@qq.com

**Comment by CURRENTF** [comment]
你好，首先你给的图里面展示的代码片段是输出，而不是读入。sub_data的代码现在已经更新到库里，直接在dataset-v5文件夹下运行 `python generate_sub_data.py` 即可

**Comment by winnerLuo** [comment]
感谢你的回信，在您的帮助下以上问题得到了解决，但又出现了新的问题，（1）在运行train文件时，出现了sking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation。
（2）UnicodeEncodeError: 'gbk' codec can't encode character '\xa5' in position 2585: illegal multibyte sequence
（貌似是数据集的问题）
![1](https://github.com/CURRENTF/HRN/assets/70368328/65c19284-7865-437d-ac67-9817b285ae1b)
![2](https://github.com/CURRENTF/HRN/assets/70368328/52af00f6-baac-4019-842f-54af73855b14)
期待你的回复。
